apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gods-app
  namespace: argocd-system
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: argocd-system
    server: https://kubernetes.default.svc
  project: default
  source:
    path: apps
    repoURL: https://github.com/Pavan-Gunda/Test-HNC.git
    targetRevision: HEAD
  syncPolicy:
    automated: {}