apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-hello-hnc-pod
  namespace: argocd-system
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: demo-pavan-hnc #adjust the values as needed
    server: https://kubernetes.default.svc
  project: default
  source:
    path: deploy/pod
    repoURL: https://github.com/Pavan-Gunda/Test-HNC
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true